sopman/Models/CompanySetup.cs
using System;
namespace sopman.Models
{
    public class CompanySetup
    {
        public CompanySetup()
        {
        }
    }
}

sopman/Models/ManageViewModels/PeopleViewModel.cs
using System;
namespace sopman.Models.ManageViewModels
{
    public class PeopleViewModel
    {
        
    }
}

sopman/Models/SetupViewModels/CompanySetupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace sopman.Models.SetupViewModels
{
    public class CompanySetupViewModel
    {

        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        [Required]
        [Display(Name = "Company Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Logo Upload")]
        [FileExtensions(Extensions = "jpg,jpeg")]
        public IFormFile Logo { get; set; }

        [Required]
        [Display(Name = "Logo Upload")]
        [FileExtensions(Extensions = "jpg,jpeg, png")]
        public IFormFile File { get; set; }


        public string FileURL { get; set; }
        //public string Logo { get; set; }

        [Display(Name = "SOP Number Format")]
        public string SOPNumberFormat { get; set; }

        [Display(Name = "SOP Start Number")]
        public string SOPStartNumber { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Second Name")]
        public string SecondName { get; set; }


    }

}

sopman/Models/SetupViewModels/OrgStructureViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
namespace sopman.Models.SetupViewModels
{
    public class OrgStructureViewModel
    {
        
    }
}

sopman/Models/SetupViewModels/PeopleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using sopman.Models.AccountViewModels;
            
namespace sopman.Models.SetupViewModels
                                             
{
    public class SetupPeopleViewModel
    {
        public List<RegisterSOPUserViewModel> RegisterSOPUser { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
    }
}

sopman/Models/SetupViewModels/ProcessStepsViewModel.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using HtmlHelpers.BeginCollectionItemCore;
using sopman.Models.AccountViewModels;
namespace sopman.Models.SetupViewModels
{
    public class ProcessStepsViewModel
    {
        public List<Process> Processes { get; set; } = new List<Process>();
        public List<SubProcess> SubProcesses { get; set; } = new List<SubProcess>();
    }

    public class Process {
        public int SOPTemplateProcessID { get; set; } 

        public string ProcessName { get; set; }
        public string ProcessDesc { get; set; }

        [Display(Name = "Upload files")]
        [FileExtensions(Extensions = "jpg,jpeg,png,doc,docx,pdf,xls,xlsx")]
        public IFormFile FilesString { get; set; }
        public List<RACIResponsible> Responsible { get; set; }
        public List<RACIAccountable> Accountable { get; set; }
        public List<RACIInformed> Informed { get; set; }
        public List<RACIConsulted> Consulted { get; set; }

        public string valuematch { get; set; }
        public string ProjectName { get; set; }
        public string ProjectId { get; set; }
        public string SOPTemplateID { get; set; }
    }
    public class SubProcess
    {
        public int SOPTemplateProcessID { get; set; }

        public string ProcessName { get; set; }
        public string ProcessDesc { get; set; }


        [Display(Name = "Upload files")]
        [FileExtensions(Extensions = "jpg,jpeg,png,doc,docx,pdf,xls,xlsx")]
        public IFormFile FilesString { get; set; }
        public List<RACIResponsible> Responsible { get; set; }
        public List<RACIAccountable> Accountable { get; set; }
        public List<RACIInformed> Informed { get; set; }
        public List<RACIConsulted> Consulted { get; set; }

        public string valuematch { get; set; }
    }

    public class RACIResponsible {
        public int RACIResID { get; set; }
        public string ProcessName { get; set; }
        public string DepartmentId { get; set; }
        public string JobTitleId { get; set; }
        public string valuematch { get; set; }
        public List<RegisterDepartmentViewModel> Departments { get; set; }
        public List<RegisterJobTitleViewModel> JobTitles { get; set; }
    }
    public class mainvaluematch {
        public string valuematch { get; set; }
    }

    public class RACIAccountable {
        public int RACIAccID { get; set; }
        public string DepartmentId { get; set; }
        public string JobTitleId { get; set; }
        public List<RegisterDepartmentViewModel> Departments { get; set; }
        public List<RegisterJobTitleViewModel> JobTitles { get; set; }
        public string valuematch { get; set; }
        public int SOPTemplateProcessID { get; set; }
    }

    public class RACIInformed
    {
        public int RACIInfID { get; set; }
        public string ProcessName { get; set; }
        public string DepartmentId { get; set; }
        public string JobTitleId { get; set; }
        public string valuematch { get; set; }
        public List<RegisterDepartmentViewModel> Departments { get; set; }
        public List<RegisterJobTitleViewModel> JobTitles { get; set; }
        public int SOPTemplateProcessID { get; set; }
    }
    public class RACIConsulted
    {
        public int RACIConId { get; set; }
        public string DepartmentId { get; set; }
        public string JobTitleId { get; set; }
        public List<RegisterDepartmentViewModel> Departments { get; set; }
        public List<RegisterJobTitleViewModel> JobTitles { get; set; }
        public string valuematch { get; set; }
        public int SOPTemplateProcessID { get; set; }
    }
}

sopman/Models/SetupViewModels/SOPTopTemplateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
namespace sopman.Models.SetupViewModels
{
    public class SOPTopTemplateViewModel
    {
        public int TopTempId { get; set; }
        public string SOPName { get; set; }

        [Display(Name = "Limit Characters")]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public int SOPNameLimit { get; set; }

        public string SOPCodePrefix { get; set; }

        public string SOPCodeSuffix { get; set; }

        public int SOPAllowCode { get; set; }

        public string SOPAllowCodeLimit { get; set; }

        public virtual IEnumerable<Section> Sections { get; set; }



    }
}

sopman/Controllers/SetupController.cs
using System;
using System.IO;
using System.Web;
using System.Data;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using LumenWorks.Framework.IO.Csv;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using sopman.Models;
using sopman.Data;
using sopman.Models.AccountViewModels;
using sopman.Models.SetupViewModels;
using sopman.Services;
using SendGrid;
using SendGrid.Helpers.Mail;
using CsvHelper;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using LogLevel = Microsoft.Extensions.Logging.LogLevel;
namespace sopman.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class SetupController : Controller
    {

        CloudStorageAccount storageAccount = new CloudStorageAccount(
        new Microsoft.WindowsAzure.Storage.Auth.StorageCredentials(
                "sopman",
                "RCmOo1xCGu7FIx0wZ3H4wNK4Y0MNtcj5chzAMWlU2GQjC/ehnsiSD9MTuHFGCUDf2sPguMByyX7VrjlQpq4/FA=="), true);

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IConfiguration _configuration;

        public SetupController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment hostingEnvironment, IConfiguration configuration)
        {
            _context = context;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
            _configuration = configuration;
        }

        [TempData]
        public string ErrorMessage { get; set; }


        [HttpGet]
        [AllowAnonymous]
        public ActionResult SetupIndex()
        {
            var getuser = _userManager.GetUserId(User);

            if (_context.CompanyClaim.Any(o => o.UserId == getuser))
            {
                ViewBag.Class = "true";
                var comp = (from i in _context.CompanyClaim
                            where i.UserId == getuser
                            select i.CompanyId).Single();
                ViewBag.comp = comp;
                var logostring = (from i in _context.TheCompanyInfo
                                  where i.CompanyId == comp
                                  select i.Logo).Single();
                ViewBag.logostring = logostring;
                var theid = (from m in _context.CompanyClaim
                             where m.UserId == getuser
                             select m.CompanyId).Single();
                if (_context.SOPTopTemplates.Any(o => o.CompanyId == theid))
                {
                    ViewBag.ClassThree = "true";
                }
                if (_context.Departments.Any(o => o.CompanyId == theid))
                {
                    ViewBag.Classtwo = "true";
                }
            }
            else { }
            return View();
        }


        public async Task<IActionResult> SetupIndex(SetupIndexViewModel model)
        {

            var user = await _userManager.GetUserAsync(User);
            var user_id = user.Id;


            var modules = (from i in _context.CompanyClaim
                           where i.UserId == user_id
                           select i.CompanyId).Single();
            
            var logostring = (from i in _context.TheCompanyInfo
                              where i.CompanyId == modules
                              select i.Logo).Single();
            ViewBag.logostring = logostring;


            return View();

            /*

             var companies = from m in _context.TheCompanyInfo
                          select m;

             return View(model); */

        }

        [HttpGet]
        public PartialViewResult AddNumber()
        {
            return PartialView("_AddNumber", new SOPCodeBuilder());
        }

        [HttpGet]
        public PartialViewResult AddCharacter()
        {
            return PartialView("_AddCharacter", new SOPCodeBuilder());
        }

        [HttpGet]
        public PartialViewResult AddDash()
        {
            return PartialView("_AddDash", new SOPCodeBuilder());
        }

        [HttpGet]
        public PartialViewResult AddSpace()
        {
            return PartialView("_AddSpace", new SOPCodeBuilder());
        }

        [HttpGet]
        public PartialViewResult AddComma()
        {
            return PartialView("_AddComma", new SOPCodeBuilder());
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult CompanySetup()
        {
            var ordervm = new CompanySetupViewModel();
            var getuser = _userManager.GetUserId(User);



            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SOPAdmin")]
        public async Task<IActionResult> CompanySetup([Bind("Id,Name,Logo,SOPNumberFormat,SOPStartNumber,UserId")] ApplicationDbContext.CompanyInfo company, IFormFile file,  [Bind("ClaimId,CompanyId,UserId,FirstName,SecondName")] ApplicationDbContext.ClaimComp claim, [Bind(Prefix = "SOPCode")]IEnumerable<SOPCodeBuilder> sopcodebuild)
        {
            var user = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {

                var getname = Request.Form["Name"];
                var getfile = Request.Form["file"];

                if(file != null){
                    CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
                    CloudBlobContainer container = blobClient.GetContainerReference("logos");

                    await container.CreateIfNotExistsAsync();

                    await container.SetPermissionsAsync(new BlobContainerPermissions
                    {
                        PublicAccess = BlobContainerPublicAccessType.Blob
                    });

                    CloudBlockBlob blockBlob = container.GetBlockBlobReference(getname + "logo" + file.FileName);

                    await blockBlob.UploadFromStreamAsync(file.OpenReadStream());
                    _context.TheCompanyInfo.Select(u => u.Logo);
                    company.Logo = getname + "logo" + file.FileName;
                }


                _context.TheCompanyInfo.Select(u => u.UserId);
                var user_id = user.Id;
                company.UserId = user_id;
                claim.UserId = user_id;

                _context.CompanyClaim.Select(u => u.CompanyId);
                var comp_id = company.CompanyId;
                claim.CompanyId = comp_id;

                _context.CompanyClaim.Select(u => u.UserId);
                claim.UserId = user_id;

                _context.TheCompanyInfo.Select(u => u.SOPNumberFormat);
                var sopfrom = Request.Form["SOPNumberFormat"];
                company.SOPNumberFormat = sopfrom;
               
                _context.Add(company);
                await _context.SaveChangesAsync();
                var getid = (from i in _context.TheCompanyInfo
                             where i.UserId == user_id
                             select i.CompanyId).Single();

                _context.CompanyClaim.Select(u => u.CompanyId);
                claim.CompanyId = getid;

                _context.Add(claim);
                await _context.SaveChangesAsync();

                foreach(var item in sopcodebuild){

                    ApplicationDbContext.SOPNumbering number = new ApplicationDbContext.SOPNumbering();

                    var getcompid = (from i in _context.TheCompanyInfo
                                     where i.UserId == user_id
                                     select i.CompanyId).Single();

                    number.CompanyId = getcompid;

                    if(item.InputValue == "0"){
                        var numbervalue = "0";
                        number.InputValue = numbervalue;
                        Console.WriteLine("Number:");
                        Console.WriteLine(number.InputValue);
                        _context.Add(number);
                    }
                    if (item.InputValue == "A")
                    {
                        var charvalue = "A";
                        number.InputValue = charvalue;
                        Console.WriteLine("Character:");
                        Console.WriteLine(number.InputValue);
                        _context.Add(number);
                    }
                    if (item.InputValue == "-")
                    {
                        var dashvalue = "-";
                        number.InputValue = dashvalue;
                        Console.WriteLine("Dash:");
                        Console.WriteLine(number.InputValue);
                        _context.Add(number);
                    }
                    if (item.InputValue == "space")
                    {
                        var spacevalue = "space";
                        number.InputValue = spacevalue;
                        Console.WriteLine("Space:");
                        Console.WriteLine(number.InputValue);
                        _context.Add(number);
                    }
                    if (item.InputValue == ",")
                    {
                        var commavalue = ",";
                        number.InputValue = commavalue;
                        Console.WriteLine("Comma:");
                        Console.WriteLine(number.InputValue);
                        _context.Add(number);
                    }

sopman/Views/Setup/NewTemplate.cshtml
@model IEnumerable<sopman.Models.SetupViewModels.SopTemplate>
@using HtmlHelpers.BeginCollectionItemCore
@{
    ViewData["Title"] = "New Template";

}

@using (Html.BeginForm("NewTemplate", "Setup", FormMethod.Post)){
<div class="container sop-builder">
    <div class="row header-white">
        <div class="col-12">
            <h1>Stage 1 - add information</h1>
        </div>
        <div class="col-12 rest-of-form">
            
        </div>
        <div class="col-12">
            <hr>
        </div>
        <div class="col-12 approvers-of-form">
            <a class="btn btn-default add-approver">Add Approver</a>
        </div>
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row white-bg">
        <div class="col-12 no-pad">
            <div class="row inner-form">
                @foreach(var item in Model){
                    <div class="col-12 col-md-8 section-row">
                        <h4>@Html.DisplayFor(modelItem => item.SectionText)</h4>
                        @foreach(var subitem in (ViewBag.GetTabs)){
                            if(subitem.valuematch == item.valuematch){
                               var text = @subitem.TableHTML.Replace(" ", "");
                               <input class="form-control limit-form" type="text" name="TableHTML-@text" value="@subitem.TableHTML" >                              
                               <div class="row">
                                   <div class="col-12 col-md-10 new-table">
                                        <div class="table table-@text">
                                            <div class="columns-row">
                                            </div>
                                            <div class="new-row">
                                            </div>
                                        </div>
                                   </div>
                                   <div class="col-12 col-md-2">
                                        <button id="add-table" class="add-@text add-a-col" type="button">Add Column</button>
                                   </div>
                                   <div class="col-12 col-md-12">
                                        <button id="add-table" class="add-row-@text" type="button">Add Row</button>
                                   </div>
                                </div>
                                <script>
                                    $(document).ready(function () {
                                        var url = '@Url.Action("AddColumns")';
                                        var urltwo = '@Url.Action("AddTable")';
                                        var form = $('form');
                                        var recipients = $('.table-@text .columns-row'); 
                                        var recipientstwo = $('.table-@text .new-row'); 
                                        $(".add-@text").click(function(){
                                            $.post(url, function(response) {
                                                recipients.append(response);  
                                                form.data('validator', null);
                                                $.validator.unobtrusive.parse(form); 
                                            }); 
                                        });
                                        $(".add-row-@text").click(function(){  
                                            var clone = $('.table-@text .columns-row .a-col').length;
                                            console.log(clone);
                                            for (var i = 0; i < clone; i++){
                                                $.post(urltwo, function(response) {
                                                    recipientstwo.append(response);  
                                                    form.data('validator', null);
                                                    $.validator.unobtrusive.parse(form); 
                                                }); 
                                            }; 
                                        }); 
                                    });
                                </script>
                            }
                        }
                        @foreach(var subitem in (ViewBag.GetSin)){
                            if(subitem.valuematch == item.valuematch){
                                var text = @subitem.SingleLinkTextBlock.Replace(" ", "");
                                <input class="form-control limit-form" type="text" name="SingleLinkTextBlock-@text" placeholder="@subitem.SingleLinkTextBlock" >
                            }
                        } 
                        @foreach(var subitem in (ViewBag.GetMul)){
                            if(subitem.valuematch == item.valuematch){
                                var text = @subitem.MultilineTextBlock.Replace(" ", "");
                                <textarea name="MultilineTextBlock-@text" class="form-control limit-form" placeholder="@subitem.MultilineTextBlock"> </textarea>   
                            }
                        }
                    </div>
                }
                <div class="form-group bottom-row submit-row">
                    <div class="col-12 float-to-right">
                        <input type="submit" class="btn btn-default" value="save and continue" />
                    </div>
                </div>
            </div>
          </div>
    </div>
</div>
  }

@section Scripts {
<script>
    $(document).ready(function () {
        var urltop = '@Url.Action("AddTemp")';
        var form = $('form');
        var recipientstop = $('.rest-of-form'); 
        $.post(urltop, function(response) {
            recipientstop.append(response);  
            form.data('validator', null);
            $.validator.unobtrusive.parse(form); 
        }); 
    });
    $(document).ready(function () {
            var urlapp = '@Url.Action("AddApprover")';
            var form = $('form');
            var recipientstwo = $('.approvers-of-form');
            $('.add-approver').click(function() {
                $.post(urlapp, function(response) {
                    recipientstwo.append(response);
                    // Reparse the validator for client side validation
                    form.data('validator', null);
                    $.validator.unobtrusive.parse(form);
                });
            });  
        });
</script>
}

sopman/Views/Setup/People.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<sopman.Models.AccountViewModels.RegisterSOPUserViewModel> 
@{
    ViewData["Title"] = "People";
}
<div class="container people-div">
    <div class="row">
        <div class="col-12 col-md-6">
            <a class="people-btn" asp-area="" asp-controller="Account" asp-action="RegisterDepartment">Create Department</a>
            <a class="people-btn" asp-area="" asp-controller="Account" asp-action="RegisterJobTitle">Create Job Title</a>
            <button type="button" class="btn btn-secondary padding-left-tooltip builder-tooltip" data-toggle="tooltip" data-placement="right" title="Add Departments and jobs to your company">
                <i class="material-icons">help</i>
            </button>    
        </div>
        <div class="col-12 col-md-6">
            <a class="people-btn" asp-area="" asp-controller="Account" asp-action="RegisterSOPCreator">Create SOPCreator</a>
            <a class="people-btn" asp-area="" asp-controller="Account" asp-action="RegisterSOPUser">Create SOPUser</a>
            <button type="button" class="btn btn-secondary padding-left-tooltip builder-tooltip" data-toggle="tooltip" data-placement="left" title="Create your different user levels here">
                <i class="material-icons">help</i>
            </button> 
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="padding-top:40px; padding-left:20px;">
            <ul class="col-12 people-list">
                @foreach(var item in (ViewBag.getthepeople)){
                    foreach(var user in (ViewBag.userinfo)){
                        if(item.UserId == user.Id){
                            <li class="row">
                                <div class="col-12">
                                    <div class="row  people-row">
                                        <div class="col-12 col-md-6 people-text">
                                            <h3>@item.FirstName @item.SecondName</h3>
                                            <p>@user.Email</p>
                                            <p>
                                                @foreach(var dep in (ViewBag.deppartments)){
                                                    if(dep.DepartmentId == item.DepartmentId){
                                                        @dep.DepartmentName
                                                    }
                                                }
                                                @foreach(var job in (ViewBag.jobtitle)){
                                                    if(job.JobTitleId == item.JobTitleId){
                                                        @job.JobTitle
                                                    }
                                                }
                                            </p>
                                        </div>
                                        <div class="col-12 col-md-6">
                                            
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 people-text">
                                    <hr />
                                </div>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
    </div>
    <div class="row back-to-row">
        <div class="col-12 col-md-6">
            <a class="people-btn" asp-area="" asp-controller="Setup" asp-action="SetupIndex">Back to Setup</a>
        </div>
    </div>
</div>

sopman/Views/Setup/SOPTopTemplate.cshtml
@using Microsoft.AspNetCore.Identity
@model SOPTopTemplateViewModel

@{
    ViewData["Title"] = "SOP Template";
}

<div class="container sop-top-temp">
    <div class="row header">
        <div class="col-12">
            <h1>@ViewData["Title"]</h1>
        </div>
    </div>
    <div class="row the-form">
        <div class="col-12">
            <h3>Warning</h3>
            <p>Changing these settings will affect all existing SOPs within your organisation</p>
            <hr />
        </div>
        @using (Html.BeginForm("SOPTopTemplate", "Setup", FormMethod.Post, 
        new { @class = "form-horizontal form-sop col-12", role = "form", enctype = "multipart/form-data" }))
        {
            <div class="form-group inline-row row">
                <div class="col-12">
                    <h4>SOP Name</h4>
                </div>
            </div>
            <div class="form-group inline-row row">
                <div class="col-12 col-md-3">
                    <input type="radio" name="radiolimit" value=""  id="radiolimit"/>@Html.LabelFor(m => m.SOPNameLimit, new { @for = "radiolimit", @class="radio-label"})
                </div>
                <div class="col-12 col-md-2">
                    @Html.TextBoxFor(m => m.SOPNameLimit, new { @class = "form-control limit-form", @disabled = "disabled" })
                </div>
            </div>
            <hr />
            <!--<div class="form-group inline-row row">
                <div class="col-12">
                    <h4>SOP Code</h4>
                </div>
            </div>
            <div class="form-group inline-row row">
                <div class="col-12 col-md-6">
                    <input type="radio" name="auto-gen" value=""  id="auto-gen"/><label class="gen-radio" for="auto-gen">Use auto-generated SOP numbers</label>
                </div>
            </div>
            <div class="form-group inline-row row row-pad-left fade-bg">
                <div class="col-12 col-md-4 offset-md-1">
                    <input type="radio" name="auto-gen-pre" value=""  id="auto-gen-pre"/><label class="gen-radio-pre" for="auto-gen-pre">Use auto-generated SOP numbers</label>
                </div>
                <div class="col-12 col-md-2">
                    @Html.TextBoxFor(m => m.SOPCodePrefix, new { @class = "form-control prefix-form", @disabled = "disabled" })
                </div>
            </div>
            <div class="form-group inline-row row row-pad-left fade-bg suffix-row">
                <div class="col-12 col-md-4 offset-md-1">
                    <input type="radio" name="auto-gen-suff" value=""  id="auto-gen-suff"/><label class="gen-radio-suff" for="auto-gen-suff">Use auto-generated SOP numbers</label>
                </div>
                <div class="col-12 col-md-2">
                    @Html.TextBoxFor(m => m.SOPCodeSuffix, new { @class = "form-control suffix-form", @disabled = "disabled" })
                </div>
            </div>  
            <div class="form-group inline-row row pad-top-20">
                <div class="col-12 col-md-6">
                    <input type="radio" name="auto-gen-lim-char" value=""  id="auto-gen-lim"/><label class="gen-radio" for="auto-gen"> Allow user defined SOP codes</label>
                </div>
            </div>
            <div class="form-group inline-row row">
                <div class="col-12 col-md-4 offset-md-1">
                    <input type="radio" name="radioallowlimitcode" value=""  id="radioallowlimitcode"/><label  class="gen-radio" for="SOPAllowCodeLimit"> Limit characters</label>
                </div>
                <div class="col-12 col-md-2">
                    @Html.TextBoxFor(m => m.SOPAllowCodeLimit, new { @class = "form-control limit-form-char", @disabled = "disabled" })
                </div>
            </div> -->
            <div class="form-group submit-row">
                <div class="col-12 float-to-right">
                    <input type="submit" class="btn btn-default" value="continue" />
                </div>
            </div>
        }   
    </div>
</div>